tasky/Controllers/SprintController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using tasky.Models;
using tasky.Repository;
using tasky.ViewModels;

namespace tasky.Controllers
{
    public class SprintController : Controller
    {
        private ISprintRepository repo;
        private IReleaseRepository releaseRepo = new ReleaseRepository();
        public SprintController(ISprintRepository r)
        {
            this.repo = r;
        }

        //
        // GET: /Sprint/

        public ActionResult Index()
        {
            ICollection<Sprint> sprints = repo.FindAll();
            ICollection<SprintViewModel> sprintVMs = new List<SprintViewModel>();
            IEnumerator<Sprint> sprintIterator = sprints.GetEnumerator();
            SprintViewModel tempSprintVM;
            while (sprintIterator.MoveNext())
            {
                tempSprintVM = SprintViewModel.convertSprint(sprintIterator.Current);
                tempSprintVM.convertStoriesToVMs(repo.FindStoriesForSprint(sprintIterator.Current.id));
                sprintVMs.Add(tempSprintVM);
            }
            
            return View(sprintVMs);
        }

        //
        // GET: /Sprint/Details/5

        public ActionResult Details(int id)
        {
            Sprint sprint = repo.FindById(id);

            if (sprint == null)
            {
                return HttpNotFound();
            }

            StoryViewModel storyViewModel = new StoryViewModel();
            sprint.stories = repo.FindStoriesForSprint(id);
            SprintViewModel sprintViewModel = SprintViewModel.convertSprint(sprint);

            ICollection<StoryViewModel> stories = new List<StoryViewModel>();
            
            foreach (Story story in sprint.stories)
            {
                stories.Add(StoryViewModel.convertStory(story));
            }

            sprintViewModel.stories = stories;

            //compute the data for the burndown chart
            int totalEstimated = repo.SumTaskEstimatesForSprint(id);

            Dictionary<DateTime, int> dataMap = new Dictionary<DateTime, int>();
            foreach (var i in repo.FindTaskLogsForSprint(id))
            {
                int sum;
                if (!dataMap.TryGetValue(i.logDate, out sum))
                {
                    sum = 0;
                }
                dataMap[i.logDate] = sum + i.loggedHours;
            }

            //create the list of "actual" burndown data
            List<BurndownEntry> burndownEntries = new List<BurndownEntry>();
            int remainingHours = totalEstimated;
            foreach(DateTime d in dataMap.Keys.OrderBy(date => date)) {
                remainingHours -= dataMap[d];
                burndownEntries.Add(new BurndownEntry { date = d, remaining = remainingHours });
            }

            //create the list of "ideal" burndown data
            List<BurndownEntry> idealBurn = new List<BurndownEntry>();
            idealBurn.Add(new BurndownEntry { date = sprint.startDate, remaining = totalEstimated });
            idealBurn.Add(new BurndownEntry { date = sprint.endDate, remaining = 0 });

            ViewBag.ActualBurndownEntries = burndownEntries;
            ViewBag.IdealBurndownEntries = idealBurn;
            ViewBag.InitialEstimate = totalEstimated;
            
            return View(sprintViewModel);
        }

        //
        // GET: /Sprint/Create

        public ActionResult Create(int? releaseID=null)
        {
            if (releaseID != null)
            {
                Release currentRelease = releaseRepo.FindById((int)releaseID);
                ViewBag.currentReleaseID = currentRelease.id;
                ViewBag.releaseTitle = currentRelease.title;
            }
            else
            {
                ViewBag.ReleaseOptions = new SelectList(getReleaseOptions(), "Id", "Title");
            }
            return View();
        }

        //
        // POST: /Sprint/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Sprint sprint)
        {
            if (ModelState.IsValid)
            {
                repo.Save(sprint);
                return RedirectToAction("Index");
            }

            return View(sprint);
        }

        //
        // GET: /Sprint/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Sprint sprint = repo.FindById(id);

            if (sprint == null)
            {
                return HttpNotFound();
            }
            ViewBag.ReleaseOptions = new SelectList(getReleaseOptions(), "Id", "Title");
            return View(sprint);
        }

        //
        // POST: /Sprint/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Sprint sprint)
        {
            if (ModelState.IsValid)
            {
                repo.Save(sprint);
                return RedirectToAction("Index");
            }
            return View(sprint);
        }


        //
        // GET: /Sprint/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Sprint sprint = repo.FindById(id);

            if (sprint == null)
            {
                return HttpNotFound();
            }
            return View(sprint);
        }

        //
        // POST: /Sprint/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            repo.Delete(id);
            return RedirectToAction("Index");
        }

        [HttpPost]
        public void UpdateStories(int id, List<Story> stories)
        {
            repo.SaveStories(id, stories);
        }

        public class BurndownEntry
        {
            public DateTime date { get; set; }
            public int remaining { get; set; }
        }
        private ICollection<Release> getReleaseOptions()
        {
            return releaseRepo.FindAll();
        }

    }
}

tasky/Controllers/StoryController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using tasky.Models;
using tasky.Repository;
using tasky.ViewModels;

namespace tasky.Controllers
{
    public class StoryController : Controller
    {
        private static String[] StatusOptions = new String[] { "To-Do", "In Progress", "Done", "Accepted"};

        private ISprintRepository sprintRepo;
        private IStoryRepository storyRepo;
        public StoryController(ISprintRepository s,IStoryRepository r)
        {
            this.sprintRepo = s;
            this.storyRepo = r;
        }

        //
        // GET: /Story/

        public ActionResult Index(string statusFilter = "", int? sprintFilter = null)
        {
            //create a selectlist for the status options
            ViewBag.StatusOptions = new SelectList(StatusOptions);

            //create a selectlist for the sprint options - use the name of every existing sprint
            ViewBag.SprintOptions = new SelectList(getSprintOptions(), "Id","Title");

            return View(storyRepo.FindWithFilters(statusFilter, sprintFilter));
        }

        //
        // GET: /Story/Details/5


        public ActionResult Details(int id)
        {
            SprintViewModel sprintViewModel;

            Story story = storyRepo.FindById(id);
            if (story == null)
            {
                return HttpNotFound();
            }
            story.tasks = storyRepo.FindTasksForStory(id);

            StoryViewModel storyViewModel = StoryViewModel.convertStory(story);
            sprintViewModel = SprintViewModel.convertSprint(story.sprint);
            storyViewModel.sprintViewModel = sprintViewModel;
            ICollection<TaskViewModel> tasks = new List<TaskViewModel>();

            foreach(Task task in story.tasks)
            {
                tasks.Add(TaskViewModel.convertTask(task));
            }

            storyViewModel.tasks = tasks;
            return View(storyViewModel);
        }

        //
        // GET: /Story/Create

        public ActionResult Create(int? sprintID = null)
        {
            ViewBag.StatusOptions = new SelectList(StatusOptions);
            if (sprintID != null)
            {
                Sprint currentSprint = sprintRepo.FindById((int)sprintID);
                ViewBag.currentSprintID = currentSprint.id;
                ViewBag.sprintTitle = currentSprint.title;
            }
            else
            {
                //create a selectlist for the sprint options - use the name of every existing sprint
                ViewBag.SprintOptions = new SelectList(getSprintOptions(), "Id", "Title");
            }

            //create a selectlist for the status options
            ViewBag.StatusOptions = new SelectList(StatusOptions);
            return View();
        }

        //
        // POST: /Story/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Story story)
        {
            if (ModelState.IsValid)
            {
                storyRepo.Save(story);
                return RedirectToAction("Index");
            }
            return View(story);
        }

        //
        // GET: /Story/Edit/5

        public ActionResult Edit(int id = 0)
        {
            Story story = storyRepo.FindById(id);
            if (story == null)
            {
                return HttpNotFound();
            }

            //create a selectlist for the status options
            ViewBag.StatusOptions = new SelectList(StatusOptions);

            //create a selectlist for the sprint options - use the name of every existing sprint
            ViewBag.SprintOptions = new SelectList(getSprintOptions(), "Id", "Title");

            return View(story);
        }

        //
        // POST: /Story/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Story story)
        {
            if (ModelState.IsValid)
            {
                storyRepo.Save(story);
                return RedirectToAction("Index");
            }

            return View(story);
        }

        //
        // GET: /Story/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Story story = storyRepo.FindById(id);
            if (story == null)
            {
                return HttpNotFound();
            }
            return View(story);
        }

        //
        // POST: /Story/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            storyRepo.Delete(id);
            return RedirectToAction("Index");
        }

        //queries all stories, groups them by sprint name, then returns the sprint names
        private ICollection<Sprint> getSprintOptions()
        {
            return sprintRepo.FindAll();
        }
    }
}

tasky/Controllers/TaskController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using tasky.Models;
using tasky.Repository;
using tasky.ViewModels;

namespace tasky.Controllers
{
    public class TaskController : Controller
    {
        private static String[] StatusOptions = new String[] { "To-Do", "In Progress", "Done", "Accepted" };

        private IStoryRepository storyRepo;
        private ITeamMemberRepository teamMemberRepo;
        private ITaskRepository taskRepo;

        public TaskController(IStoryRepository s, ITeamMemberRepository m, ITaskRepository r)
        {
            this.storyRepo = s;
            this.teamMemberRepo = m;
            this.taskRepo = r;
        }

        //
        // GET: /Task/

        public ActionResult Index(string statusFilter = "", int? teamMemberFilter = null)
        {
            //create a selectlist for the status options
            ViewBag.StatusOptions = new SelectList(StatusOptions);

            //create a selectlist for the team member options - use the name of every existing sprint
            ViewBag.TeamMemberOptions = new SelectList(getTeamMemberOptions(), "Id", "Name");

            return View(taskRepo.FindWithFilters(statusFilter, teamMemberFilter));
            //return View(db.Tasks.ToList());
        }

        //
        // GET: /Task/Details/5

        public ActionResult Details(int id = 0)
        {
            Task task = taskRepo.FindById(id);
            TaskLogViewModel taskLogVM = new TaskLogViewModel();
            

            if (task == null)
            {
                return HttpNotFound();
            }

            taskLogVM.setTaskInfo(task);
            taskLogVM.setTaskLogInfo(new TaskLog { taskId = task.id });

            return View(taskLogVM);
        }

        //
        // GET: /Task/Create

        public ActionResult Create(int? teamMemberID = null, int? storyID = null)
        {
            ViewBag.StatusOptions = new SelectList(StatusOptions);
            
            if (teamMemberID != null)
            {
                TeamMember currentTeamMember = teamMemberRepo.FindById((int)teamMemberID);
                ViewBag.currentTeamMemberID = currentTeamMember.id;
                ViewBag.teamMemberName = currentTeamMember.name;
            }
            else
            {
                //create a selectlist for the team member options - use the name of every existing member
                ViewBag.TeamMemberOptions = new SelectList(getTeamMemberOptions(), "Id", "Name");
            }

            if (storyID != null)
            {
                Story currentStory = storyRepo.FindById((int)storyID);
                ViewBag.currentStoryID = currentStory.id;
                ViewBag.currentStoryTitle = currentStory.title;
            }
            else
            {
                ViewBag.StoryOptions = new SelectList(getStoryOptions(), "Id", "Title");
            }

            //create a selectlist for the status options
            ViewBag.StatusOptions = new SelectList(StatusOptions);
            return View();

            //List<TeamMember> TeamMemberList = db.TeamMembers.OrderBy(model => model.name).ToList();
            //ViewBag.TeamList = new SelectList(TeamMemberList, "id", "Name");
            //return View();
        }

        //
        // POST: /Task/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(Task task)
        {
            if (ModelState.IsValid)
            {
                taskRepo.Save(task);
                return RedirectToAction("Index");
            }

            return View(task);
        }

        public ActionResult LogHours(TaskLog log)
        {
            if (ModelState.IsValid)
            {
                Task task = taskRepo.FindById(log.taskId);

                if(task.Remaining_Hours > 0)
                    task.Remaining_Hours -= log.loggedHours;

                taskRepo.Log(log);
                taskRepo.Save(task);
            }
            return RedirectToAction("Details/"+log.taskId);;
        }

        //
        // GET: /Task/Edit/5

        public ActionResult Edit(int id)
        {
            Task task = taskRepo.FindById(id);
            if (task == null)
            {
                return HttpNotFound();
            }

            //create a selectlist for the status options
            ViewBag.StatusOptions = new SelectList(StatusOptions);

            //create a selectlist for the team member options - use the name of every existing member
            ViewBag.TeamMemberOptions = new SelectList(getTeamMemberOptions(), "Id", "Name");

            ViewBag.StoryOptions = new SelectList(getStoryOptions(), "Id", "Title");

            return View(task);
        }

        //
        // POST: /Task/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(Task task)
        {
            if (ModelState.IsValid)
            {
                taskRepo.Save(task);
                return RedirectToAction("Index");
            }

            return View(task);
        }

        //
        // GET: /Task/Delete/5

        public ActionResult Delete(int id = 0)
        {
            Task task = taskRepo.FindById(id);
            if (task == null)
            {
                return HttpNotFound();
            }
            return View(task);
        }

        //
        // POST: /Task/Delete/5

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            taskRepo.Delete(id);
            return RedirectToAction("Index");
        }

        //queries all tasks, groups them by team member name, then returns the names
        private ICollection<TeamMember> getTeamMemberOptions()
        {
            return teamMemberRepo.FindAll();
        }

        private ICollection<Story> getStoryOptions()
        {
            return storyRepo.FindAll();
        }
    }
}

tasky/Views/Story/Create.cshtml
@model tasky.Models.Story

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Story</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.title)
            @Html.ValidationMessageFor(model => model.title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.description)
            @Html.ValidationMessageFor(model => model.description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.points)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.points)
            @Html.ValidationMessageFor(model => model.points)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.status)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.status, 
                      ViewBag.StatusOptions as SelectList, 
                      "-- Select a status--",
                      new { @class = "editor-textbox" })
            @Html.ValidationMessageFor(model => model.status)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.sprint)
        </div>
        <div class="editor-field">
            @if (ViewBag.currentSprintID != null)
            {
                @Html.HiddenFor(model => model.sprintId, new { value = ViewBag.currentSprintID })
                @ViewBag.SprintTitle
            }
            else 
            {
                @Html.DropDownListFor(model => model.sprintId, ViewBag.SprintOptions as SelectList, "-- Filter Sprint --")
            }                               
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

tasky/Views/Story/Delete.cshtml
@model tasky.Models.Story

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Story</legend>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.description)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.description)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.title)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.title)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.points)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.points)
    </div>

    <div class="display-label">
         @Html.DisplayNameFor(model => model.status)
    </div>
    <div class="display-field">
        @Html.DisplayFor(model => model.status)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

tasky/Views/Story/Details.cshtml
@model tasky.ViewModels.StoryViewModel

@{
    ViewBag.Title = "Details";
}

<div class="container">
    <div class="span-5">
        <h2>@Html.DisplayFor(model => model.title)</h2>
        <div>
            @Html.DisplayNameFor(model => model.sprintViewModel.title):
            @Html.ActionLink((string)Model.sprintViewModel.title, "Details", "Sprint", new {id = Model.sprintViewModel.id}, null)

            @Html.DisplayNameFor(model => model.points):
            @Html.DisplayFor(model => model.points)
        </div>

        <div>
            @Html.DisplayNameFor(model => model.status):
            @Html.DisplayFor(model => model.status)
        </div>
        <div>
            @Html.DisplayNameFor(model => model.description):
            @Html.DisplayFor(model => model.description)
        </div>

        <div>
            @Html.ActionLink("Edit", "Edit", new { id=Model.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=Model.id })
            @Html.ActionLink("New Task", "Create", "Task")
        </div>
    </div>
</div>
</br>
<hr class="hrStyleOne" />
<div class="container">
    <h3>Tasks</h3>
    <div class="taskList">

        <script id='itemTemplate' type='text/template'>
                <% for (var i = 0; i < tasks.length; i++) { %>
                    <% var task = tasks[i]; %>
                    <% var chBoxStatus = "" %>
                    <% if(task.get("Status") == "Done") { chBoxStatus = "checked";}%>
                    <% console.log(task) %>
                        <div class="taskItem">
                            <div class='<%= chBoxStatus %>'>
                                <input type="checkbox" class="task-check" id='<%= task.id %>' <%= chBoxStatus %>/>
                                    Task: <a href='/Task/Details/<%= task.id %>'> <%= task.get("Title") %></a>
                            </div>
                        </div>
                <% } %>
        </script>

    </div>
</div>
@section Scripts {
    <script type="text/javascript">
        var taskdata = @Html.Raw(Json.Encode(Model.tasks));

        var c = new TaskList(taskdata);
        console.log(c);

        $(document).on("ready", function() {
            var taskView = new TaskListView({ items: c, el:$(".taskList") })
            taskView.render();

        });
    </script>
}

tasky/Views/Story/Edit.cshtml
@model tasky.Models.Story

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm()) {
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)

    <fieldset>
        <legend>Story</legend>

        @Html.HiddenFor(model => model.id)

        <div class="editor-label">
            @Html.LabelFor(model => model.title)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.title)
            @Html.ValidationMessageFor(model => model.title)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.description)
        </div>
        <div class="editor-field">
            @Html.TextAreaFor(model => model.description)
            @Html.ValidationMessageFor(model => model.description)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.points)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.points)
            @Html.ValidationMessageFor(model => model.points)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.status)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.status, 
                      ViewBag.StatusOptions as SelectList, 
                      "-- Select a status--",
                      new { @class = "editor-textbox" })
            @Html.ValidationMessageFor(model => model.status)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.sprint)
        </div>
        <div class="editor-field">
            @Html.DropDownListFor(model => model.sprintId, ViewBag.SprintOptions as SelectList, "-- Filter Sprint --")                  
        </div>
        
        <div class="editor-label">
           @Html.ActionLink("Create Task", "Create", "Task", new {storyId = Model.id}, null)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

tasky/Views/Story/Index.cshtml
@model IEnumerable<tasky.Models.Story>

@{
    ViewBag.Title = "Index";
}

<h2>Story Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index","Story",FormMethod.Get))
{
    @Html.DropDownList("StatusFilter", ViewBag.StatusOptions as SelectList, "-- Filter Status --")
    @Html.DropDownList("SprintFilter", ViewBag.SprintOptions as SelectList, "-- Filter Sprint --")
    <input type="submit" value="Filter" />
}

<table>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.title)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.points)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.status)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.sprint.title)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.title)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.points)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.status)
        </td>
        <th>
            @Html.DisplayFor(modelItem => item.sprint.title)
        </th>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            @Html.ActionLink("Details", "Details", new { id=item.id }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>